import Foundation

class LevelsInfo{
    let premiaImagesList = [["artist_0_1_mumitrol"],["artist_1_1_pugacheva","artist_1_5_leps","artist_1_4_mihaylov","artist_1_2_timati","artist_1_6_elka","artist_1_7_bilan","artist_1_8_shnur","artist_1_9_gradskiy"],["artist_2_1_pelagya","artist_2_2_chayvdvoem","artist_2_3_nyusha","artist_2_4_shufutinskij","artist_2_5_mashinavremeni","artist_2_6_kirkorov","artist_2_7_maksim","artist_2_8_kasta","artist_2_9_glukoza","artist_2_10_zakirova","artist_2_11_taty","artist_2_12_kino","artist_2_13_baskov","artist_2_14_agutin","artist_2_15_guf","artist_2_16_nikolaev","artist_2_17_boiarskij","artist_2_18_vaenga"],
    ["artist_3_1_vysockij","artist_3_2_meladze","artist_3_3_splin","artist_3_4_rozenbaum","artist_3_5_basta","artist_3_6_korolishut","artist_3_7_lazarev","artist_3_8_decl","artist_3_9_potapinastia","artist_3_10_rukivverh","artist_3_11_uma2rman","artist_3_12_viagra","artist_3_13_ariya","artist_3_14_lolita","artist_3_15_antonov","artist_3_16_sergey","artist_3_17_gazmanov","artist_3_18_bg"],
    ["artist_4_1_ivanushki","artist_4_2_ddt","artist_4_3_agatakristi","artist_4_4_vitas","artist_4_5_zverev","artist_4_6_gurcheno","artist_4_7_discotekaavariya","artist_4_8_fadeev","artist_4_9_moiseev","artist_4_10_friske","artist_4_11_kobzon","artist_4_12_peha","artist_4_13_lube","artist_4_14_zemfira","artist_4_15_trofim","artist_4_16_sukachev","artist_4_17_penkin","artist_4_18_naiv"],
    ["artist_5_1_leontiv","artist_5_2_faktor2","artist_5_3_varum","artist_5_4_vitiaak","artist_5_5_brezhneva","artist_5_6_aguzarova","artist_5_7_bratiagrim","artist_5_8_valeria","artist_5_9_koroltva","artist_5_10_piknik","artist_5_11_kadeshiva","artist_5_12_rotary","artist_5_13_ryso","artist_5_14_reflex","artist_5_15_babkina","artist_5_16_serov","artist_5_17_chaif","artist_5_18_raspytina"], ["artist_6_1_serduchka","artist_6_2_qest pistoles","artist_6_3_hifi","artist_6_4_koroziametalla","artist_6_5_dzhigurda","artist_6_6_nana","artist_6_7_shura","artist_6_8_laskoviymaj","artist_6_9_tokarev"], [""]]
    
    let correctAnswersList = [[["мумий тролль"]],
                              [["пугачева", "алла пугачева", "алла борисовна","алла"],["лепс", "лепс григорий", "григорий лепс", "григорий лепсверидзе", "плепс", "лепсверидзе григорий"],["стас михайлов", "михайлов", "станислав михайлов", "михайлов станислав"],["тимати", "тимур юнусов", "Timati", "тимур сказка", "тимур беноевский", "теймураз"],["елка", "елизавета иванцив", "иванцив елизавета", "иванцив лиза", "лиза иванцив", "иванцив"],["дима билан", "дима белан", "виктор билан", "виктор белан", "билан дима", "белан дима", "билан виктор", "белан виктор", "билан", "белан"],["сергей шнуров", "шнур", "ленинград", "шнуров сергей","шнуров"],["градский","александр градский", "градский александр", "александр фрадкин", "фрадкин александр", "славяне", "скоморохи"]],
                              [["пелагея", "телегина", "пелагея телегина", "телегина пелагея", "смирнова полина", "полина смирнова"], ["чай вдвоем"], ["нюша"], ["шуфутинский", "михаил шуфутинский", "шуфутинский михаил", "миша", "михаил"], ["машина времени", "макаревич", "андрей макаревич", "макаревич андрей" ], ["филипп киркоров", "киркоров филипп", "филипп бедросович", "бедросович филипп", "филипп", "бедросович", "киркоров"], ["максим"], ["каста"], ["глюкоза"], ["наргиз","закирова","наргиз закирова","закирова наргиз"], ["тату"], ["кино", "Цой", "виктор Цой", "Цой виктор"], ["басков", "николай басков", "басков николай"], ["агутин", "леонид агутин", "агутин леонид"], ["гуф"], ["николаев", "игорь николаев", "николаев игорь"], ["боярский", "михаил боярский", "боярский михаил"], ["ваенга"]],
                              [["высоцкий", "владимир высоцкий", "высоцкий владимир"], ["меладзе", "константин меладзе", "меладзе константин"], ["сплин", "васильев", "александр васильев", "васильев александр"], ["розенбаум"], ["баста", "вася", "василий", "наггано", "василий вакуленко", "вакуленко"], ["король и шут", "киш", "горшок", "князь", "князев", "горшенев"], ["сергей лазарев", "лазарев сергей", "лазарев"], ["децл","кирилл толмацкий","толмацкий кирилл", "толмацкий"], ["потап и настя", "настя и потап", "потап", "потап и настя каменских"], ["руки вверх", "жуков", "сергей жуков", "жуков сергей"], ["уматурман", "ума2рман"], ["виагра"], ["ария", "кипелов"], ["лолита", "милявская", "милявская лолита", "милявская"], ["антонов"], ["серега", "серёга"], ["газманов", "олег газманов", "газманов олег"], ["гребенщиков", "борис гребенщиков", "бг"]],
                              [["иванушки"], ["ддт", "юрий шевчук", "шевчук юрий", "шевчук"], ["агата кристи", "самойловы", "самойлов", "братья самойловы"], ["витас"], ["зверев", "сергей зверев", "зверев сергей"], ["гурченко", "людмила гурченко", "гурченко людмила"], ["дискотека авария"], ["фадеев", "максим фадеев", "фадеев максим"], ["моисеев", "борис моисеев", "моисеев борис"], ["фриске", "жанна фриске", "фриске жанна"], ["кобзон", "иосиф кобзон", "кобзон иосиф"], ["эдита пьеха", "пьеха", "пьеха эдита"], ["любэ", "расторгуев", "николай расторгуев", "расторгуев николай"], ["земфира"], ["трофим", "сергей трофимов", "трофимов сергей"], ["сукачев", "гарик сукачев", "сукачев гарик", "неприкосаемые"], ["пенкин", "сергей пенкин", "пенкин сергей"], ["наив"]],
                              [["леонтьев"], ["фактор 2", "фактор два", "фактор2"], ["варум", "анжелика варум", "варум анжелика"], ["витя ак", "витяак", "витя", "ак-47", "ак", "ак 47"], ["вера брежнева", "брежнева", "брежнева вера"], ["агузарова", "жанна агузарова", "агузарова жанна"], ["братья грим", "грим"], ["валерия", "валерия перфилова", "перфилова валерия"], ["королева", "королёва", "наташа королева", "наташа королёва", "наталия королева", "наталья королева", "наталья королёва", "наталия королёва"], ["пикник", "эдмунд шклярский", "шклярский", "шклярский эдмунд"], ["кадышева", "надежда кадышева", "кадышева надежда"], ["софия ротару", "ротару", "ротару софия"], ["авраам руссо", "руссо", "авраам", "руссо авраам"], ["рефлекс"], ["бабкина", "надежда бабкина", "бабкина надежда"], ["серов"], ["чайф"], ["распутина", "маша распутина", "распутина маша"]],
                              [["сердючка", "верка сердючка", "сердючка верка"], ["quest pistols", "квестпистолс","квест пистолс"], ["Hi-Fi", "хайфай", "хай фай", "хай-фай", "hi fi"], ["коррозия металла", "паук"], ["джигурда"], ["нана"], ["шура"], ["ласковый май", "юрий шатунов", "шатунов", "шатунов юра"], ["токарев", "вилли токарев", "токарев вилли"]],
                              [[""]]]
    
    let AlbomsList = [["Альбом: Морская\nПесня: Владивосток 2000"],
                      ["Альбом: Да!\nПесня: Позови меня с собой", "Альбом: На струнах дождя...\nПесня: Рюмка водки на столе","Альбом: Берега мечты\nПесня: Всё для тебя","Альбом: Black Star\nПесня: В Клубе","Альбом: Точки расставлены\nПесня: Прованс","Альбом: Я ночной хулиган\nПесня: Я ночной хулиган","Альбом: Для миллионов\nПесня: Менеджер","Альбом: ЖИВьЁМ в России\nПесня: Как молоды мы были..."],
                      ["Альбом: Девушкины песни\nПесня: Казак","Альбом: Ласковая моя\nПесня: Ласковая моя","Альбом: Объединение\nПесня: Наедине","Альбом: Гуляй, душа\nПесня: Третье сентября","Альбом: В круге света\nПесня: Герои вчерашних дней","Альбом: Незнакомка\nПесня: Роза чайная","Альбом: Трудный возраст\nПесня: Знаешь ли ты","Альбом: Громче воды, выше травы\nПесня: Куда надо смотреть","Альбом: Москва\nПесня: Снег идёт","Альбом: Шум сердца\nПесня: Ты - моя нежность","Альбом: 200 по встречной\nПесня: Я сошла с ума","Альбом: 45\nПесня: Восьмиклассница","Альбом: Посвящение\nПесня: Памяти Карузо","Альбом: Босоногий мальчик\nПесня: Хоп Хэй Лала Лэй","Альбом: Город до́рог\nПесня: Сплетни","Альбом: Дельфин и русалка\nПесня: Такси, такси","Альбом: Графский переулок\nПесня: Петербург моего одиночества","Альбом: Клавиши\nПесня: Курю"],
                      ["Альбом: Концерт в ДК Мир\nПесня: Песня о друге","Альбом: Самба белого мотылька\nПесня: Самба белого мотылька","Альбом: 25-й кадр\nПесня: Моё сердце","Альбом: Мои дворы\nПесня: Вальс-бостон","Альбом: 3\nПесня: Солнца не видно","Альбом: Как в старой сказке \nПесня: Проклятый старый дом","Альбом: The best\nПесня: В самое сердце","Альбом: Кто? Ты\nПесня: Вечеринка ","Альбом: Не пара\nПесня: Не пара ","Альбом: Без тормозов\nПесня: Ну, где же вы девчонки?","Альбом: В городе N\nПесня: Проститься","Альбом: Попытка № 5\nПесня: Что же я наделала?","Альбом: Крещение огнём\nПесня: Колизей","Альбом: Фетиш\nПесня: Прощай, оружие!","Альбом: Крыша дома твоего\nПесня: Крыша дома твоего","Альбом: The best of...\nПесня: Чёрный бумер","Альбом: Морячка\nПесня: Морячка","Альбом: Беспечный русский бродяяга\nПесня: Стаканы"],
                      ["Альбом: Твои письма\nПесня: Кукла","Альбом: Актриса Весна\nПесня: Родина","Альбом: Ураган\nПесня: Грязь","Альбом: Философия чуда\nПесня: Опера 2","Альбом: Ради тебя\nПесня: Алла","Альбом: -\nПесня: 5 минут","Альбом: Авария против!\nПесня: Пей Пиво!","Альбом: Ножницы\nПесня: Танцы на стеклах","Альбом: Праздник! Праздник!\nПесня: Голубая луна","Альбом: Жанна\nПесня: Ла-ла-ла","Альбом: Танго, Танго, Танго\nПесня: Счастье Мое","Альбом: -\nПесня: Наш сосед","Альбом: Песни о людях\nПесня: Там, за туманами","Альбом: Прости меня моя любовь\nПесня: Хочешь","Альбом: Ветер в голове\nПесня: Боже, какой пустяк","Альбом: Ночной полёт\nПесня: Моя бабушка курит трубку","Альбом: Мистер Икс\nПесня: Ария Мистера Икс","Альбом: Форева\nПесня: Я не шучу"],
                      ["Альбом: Муза\nПесня: Полет на дельтаплане","Альбом: В нашем стиле\nПесня: Красавица","Альбом: Ля-ля-фа\nПесня: Ля-ля-фа","Альбом: МегаPolice\nПесня: Оля Лукина","Альбом: Любовь спасёт мир\nПесня: Любовь спасёт мир","Альбом: Bravo\nПесня: Кошки","Альбом: Братья Грим\nПесня: Ресницы","Альбом: Страна Любви\nПесня: Часики","Альбом: Конфетти\nПесня: Маленькая страна","Альбом: Королевство кривых\nПесня: У шамана три руки","Альбом: Когда-нибудь\nПесня: Широка река","Альбом: Я: твоя любовь!\nПесня: Я назову планету","Альбом: Обручальная\nПесня: Обручальная","Альбом: Пульс\nПесня: Танцы","Альбом: Продлись, моё счастье\nПесня: Финская полька","Альбом: Я люблю тебя до слёз\nПесня: Я люблю тебя до слёз","Альбом: Время не ждёт\nПесня: Не доводи до предела","Альбом: Городская Сумасшедшая\nПесня: Клава"],
                      ["Альбом: Ха-Ра-Шо!\nПесня: Все будет хорошо","Альбом: Для тебя\nПесня: Я устал","Альбом: Первый контакт\nПесня: Ты прости","Альбом: Орден Сатаны\nПесня: Фантом","Альбом: Волчья кровь\nПесня: Огонь любви","Альбом: Фаина\nПесня: Фаина","Альбом: Благодарю. Второе дыхание\nПесня: Твори добро","Альбом: Белые розы\nПесня: Седая ночь","Альбом: Над гудзоном\nПесня: Рыбацкая"],
                      [""]]
    
    let premiasAmount = 8
    let levelsAmount = { () -> Int in
        var amount = 0
        for i in 1..<LevelsInfo().AlbomsList.count-1{
            amount += LevelsInfo().AlbomsList[i].count
        }
        return amount
    }
    
    var levelSolvedList = [[false],
                           [false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],
                           [false,false,false,false,false,false,false,false,false],[false]]
    var helpsUsed = [[[false,false,false,false]],
                     [[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]],
                     [[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]],
                     [[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]],
                     [[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]],
                     [[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]],
                     [[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false],[false,false,false,false]], [[false,false,false,false]]]
    
    let premiaDisksList = [["obychenie_0", "obychenie_1"], ["lvl11","lvl12","lvl13","lvl14","lvl15","lvl16","lvl17","lvl18","lvl19"],["lvl21","lvl22","lvl23","lvl24","lvl25","lvl26","lvl27","lvl28","lvl29","lvl210","lvl211","lvl212","lvl213","lvl214","lvl215","lvl216","lvl217","lvl218","lvl219"],["3lvl1","3lvl2","3lvl2","3lvl3","3lvl4","3lvl5","3lvl6","3lvl7","3lvl8","3lvl9","3lvl11","3lvl12","3lvl13","3lvl14","3lvl15","3lvl16","3lvl17","3lvl18","3lvl19"],["4lvl1","4lvl2","4lvl2","4lvl3","4lvl4","4lvl5","4lvl6","4lvl7","4lvl8","4lvl9","4lvl11","4lvl12","4lvl13","4lvl14","4lvl15","4lvl16","4lvl17","4lvl18","4lvl19"],["5lvl1","5lvl2","5lvl2","5lvl3","5lvl4","5lvl5","5lvl6","5lvl7","5lvl8","5lvl9","5lvl11","5lvl12","5lvl13","5lvl14","5lvl15","5lvl16","5lvl17","5lvl18","5lvl19"],["6lvl1","6lvl2","6lvl2","6lvl3","6lvl4","6lvl5","6lvl6","6lvl7","6lvl8","6lvl9"],["7lvl0"]]
    let premiaDisksListClosed = ["obychenie_0","lvl11","lvl20","3lvl0","4lvl0","5lvl0","6lvl0","7lvl0"]
    
    let premiaIsOpendList = [true, true, false, false, false, false, false, false]
}
